---
- name: Setup dotfiles
  hosts: localhost
  tasks:
    - name: Ensure config directories exist
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: "0755"
      with_items:
        - .config
        - .config/git
        - .config/zsh
        - .local/share/zsh # zsh用の追加ディレクトリ

    - name: Copy dotfiles to home directory
      ansible.builtin.copy:
        src: "files/dotfiles/{{ item }}"
        dest: "{{ ansible_env.HOME }}/.{{ item }}"
        mode: "0644"
      with_items:
        - gitconfig
        - profile
        - vimrc
        - zprofile
        - zshrc

    - name: Set zsh as default shell
      ansible.builtin.command: chsh -s /bin/zsh
      when: ansible_user_shell != '/bin/zsh'
      become: true # この操作にはsudo権限が必要

    - name: Install zsh plugins if using oh-my-zsh
      ansible.builtin.git:
        repo: "{{ item.repo }}"
        dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/plugins/{{ item.name }}"
      with_items:
        - {
            name: "zsh-autosuggestions",
            repo: "https://github.com/zsh-users/zsh-autosuggestions.git",
          }
        - {
            name: "zsh-syntax-highlighting",
            repo: "https://github.com/zsh-users/zsh-syntax-highlighting.git",
          }
      when: "'oh-my-zsh' in lookup('file', 'files/dotfiles/zshrc')"
