---
- name: Setup Homebrew packages on macOS
  hosts: localhost
  become: false # macOSではsudoを使用しない
  vars:
    homebrew_taps:
      - homebrew/core
      - homebrew/cask
      - dart-lang/dart
      - leoafarias/fvm
      - shivammathur/php

    homebrew_packages:
      - act
      - ansible
      - cocoapods
      - coreutils
      - dart
      - ffmpeg
      - fish
      - git-lfs
      - gobject-introspection
      - guile
      - inetutils
      - jq
      - jsoncpp
      - fvm
      - mint
      - mkcert
      - nodebrew
      - nss
      - nvm
      - openjdk
      - openssl@1.1
      - openvino
      - pnpm
      - python@3.12
      - rbenv
      - rswift
      - php@7.4
      - tokei
      - tree
      - zsh-autosuggestions

    homebrew_cask_packages:
      - docker
      - iterm2
      - slack
      - github-copilot-for-xcode
      - google-chrome
      - inkscape
      - ngrok
      - qlmarkdown
      - xcodes
      - visual-studio-code
      # 必要なアプリケーションを追加

  tasks:
    - name: Ensure Homebrew taps are added
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_taps }}"

    - name: Update Homebrew and upgrade all packages
      community.general.homebrew:
        update_homebrew: true
        upgrade_all: true

    - name: Install Homebrew packages
      community.general.homebrew:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_packages }}"

    - name: Install Homebrew Cask applications
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
      with_items: "{{ homebrew_cask_packages }}"
